### ISSUE TITLE
TrackingBot does not work for me

### ISSUE THREAD

**Issue by OskarZeballosH** [Ayanaminn/TrackingBot#1]
When I open the “TrackingBot.exe” file, it does not allow me to click on the “calibration” option. 
The “calibration” box is not as in the video S1. 
 Could you please help me?
 ![TrackingBot](https://github.com/user-attachments/assets/40c17b1a-3afe-411e-b450-d1b55044f17e)

**Comment by Ayanaminn** [comment]
Hi,

This is so strange. I could not reproduce the problem at least on my PC, everything looks normal.

Could you let me know your operation environment?  Could you reproduce it? i.e. did you try to restart the program and see if this still happens?
